###
POST http://localhost:8080/motor
Content-Type: application/json

{
  "bezeichnung": "dmotor",
  "serialNumber": 1
}

###

POST http://localhost:8080/car
Content-Type: application/json

{
  "besitzer": "dhieselmayr",
  "kennzeichen": "se-9292",
  "motor": {
    "id": 1
  }
}


###
PUT http://localhost:8080/motor
Content-Type: application/json

{
  "id": 1,
  "bezeichnung": "dieselmiesel motor V2",
  "serialNumber": 1
}

###
DELETE http://localhost:8080/motor/1
